<a href="https://colab.research.google.com/github/JapiKredi/Pinnacle_AI_program_AnalyticsVidyha/blob/main/DeepLearning_building_a_neuron_with_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import the libraries

In [ ]:
#Import the torch library followed by torch.nn library as nn
import torch
import torch.nn as nn

# Assign inputs to the neuron

In [ ]:
#Inputs to the neuron (Note: We have used random values here)
inputs = torch.tensor ([3.0,2.0,-1.0])

In [ ]:
#Create a neuron with 3 features and 1 output
neuron = nn.Linear(in_features=3,out_features=1)
output = neuron(inputs)

# Print the output

In [ ]:
#Print the final output of the neuron
print (output)

tensor([-1.6716], grad_fn=<ViewBackward0>)


# Weight of the neuron

In [ ]:
#To view the weight of the neuron
neuron.weight

Parameter containing:
tensor([[-0.4211, -0.3630,  0.1369]], requires_grad=True)

# Bias of the neuron

In [ ]:
#To view the bias of the neuron
neuron.bias

Parameter containing:
tensor([0.4546], requires_grad=True)

# Mathematical Formula:

In [ ]:
#Formula for the final output of the neuron
neuron.weight@inputs.T + neuron.bias

/tmp/ipykernel_100307/2906436700.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3641.)
  neuron.weight@inputs.T + neuron.bias


tensor([-1.6716], grad_fn=<AddBackward0>)